version: '3.8'

services:
  backend:
    container_name: bingo_backend
    build: .
    restart: always
    # ports:           <-- COMENTE ISTO (Segurança: Ninguém acessa o Python direto)
    #   - "3001:3001"  <-- COMENTE ISTO
    expose:            # <-- ADICIONE ISTO (Só o Nginx vê essa porta)
      - "3001"
    dns:
      - 8.8.8.8
    environment:
      - PORT=3001
      - URL_MONGO_SORTEIO=${URL_MONGO_SORTEIO}
      - IDSALA=${IDSALA}
    volumes:
      - ./json_data:/app/json

  nginx:
    image: nginx:alpine
    container_name: bingo_nginx
    restart: always
    ports:
      - "80:80"        # <-- A Porta Oficial
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Mapeie a pasta onde está seu index.html e script.js
      #- ./FrontEnd:/usr/share/nginx/html 
      - .:/usr/share/nginx/html
      # Mapeie as imagens se estiverem fora
      - ./img:/usr/share/nginx/html/img
    depends_on:
      - backend