version: '3.8'

services:
  # --- O SERVIDOR PYTHON (Sua Aplicação) ---
  backend:
    container_name: bingo_backend
    build: .
    restart: always
    # Passamos o ID da sala como variável de ambiente
    # Se não houver variável definida, usa '001' como padrão
    environment:
      - IDSALA=${IDSALA:-001}
      - PORT=3001
      - PYTHONUNBUFFERED=1
    # O comando usa a variável para iniciar a sala correta
    command: python server.py ${IDSALA:-001}
    # Expõe a porta interna apenas para o Nginx ver (segurança)
    expose:
      - "3001"
    volumes:
      # Mapeia as pastas locais para salvar os dados
      # Basta criar as pastas 'json' e 'img' na raiz do servidor
      - ./json:/app/json
      - ./img:/app/img

  # --- O NGINX (Porteiro / Web Server) ---
  nginx:
    image: nginx:alpine
    container_name: bingo_nginx
    restart: always
    ports:
      - "80:80" # Porta 80 do servidor -> Porta 80 do Nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html # Serve arquivos estáticos se precisar
    depends_on:
      - backend